### ISSUE TITLE
Add plugin to CF Community Plugins

### ISSUE THREAD

**Issue by shakuzen** [Comcast/cf-recycle-plugin#2]
It would be easier for users to install and discover this plugin if it were listed in the [CF Community Plugins](https://plugins.cloudfoundry.org/), which can be done by following the instructions in the README of https://github.com/cloudfoundry/cli-plugin-repo

**Comment by superbeeny** [comment]
Thanks and will look into it :)

**Comment by superbeeny** [comment]
Submitted PR to have plugin listed

**Comment by superbeeny** [comment]
Merged. Now listed at https://plugins.cloudfoundry.org/
