### ISSUE TITLE
Running recycle doesn't wait for app instances

### ISSUE THREAD

**Issue by rogeruiz** [Comcast/cf-recycle-plugin#3]
When running `cf recycle ${APP_NAME}` the plugin doesn't wait for the application to first have a `down` state before checking if it's `running` again.

Proposed solution here:

- Restart the application instance
- Wait for the application to have a `down` state 10sec interval
- Wait for the application to have a `running` state 10sec interval
- Continue restarting the rest of the application instances

[I forked the repo](https://github.com/rogeruiz/cf-recycle-plugin) and am hoping to implement a fix here this weekend. I'd also like to submit this to the CF plugin list (#2) if possible. I'd like to use this plugin for a CD strategy I'm working on without having to compile the releases myself and point to my fork.

**Comment by superbeeny** [comment]
sounds good, I've made some updates to make the plugin current, go ahead and make the PR

**Comment by abbyachau** [comment]
The CF CLI team received this issue in the cli-plugin-repo [#261](https://github.com/cloudfoundry/cli-plugin-repo/issues/261). Please contact us if you would like us to remove this plugin, otherwise, we've asked the OP to reach out to you directly.

**Comment by superbeeny** [comment]
The PR was never opened against this repo, I'll implement the fixes made by @rogeruiz and update the release.

**Comment by rogeruiz** [comment]
oh sorry about that @superbeeny I can point my work the main repo now.

**Comment by superbeeny** [comment]
I'm going to run some more tests, and try and reproduce the issue.

**Comment by rogeruiz** [comment]
Sounds good, I've opened the pr #5 so you can test against it. I found that the CF apps when recycled get put into a `down` state first then come back into a `running` state, but there's a wait between these states. Let me know if I can help in any other way. 👍

**Comment by superbeeny** [comment]
Thanks, can you sign off on the CLA please and I'll merge
