### ISSUE TITLE
Binaries are not available in the releases section.

### ISSUE THREAD

**Issue by rogeruiz** [Comcast/cf-recycle-plugin#4]
The readme states the binaries are available in the releases section but they're not.

**Comment by rogeruiz** [comment]
For now, these exist at https://github.com/rogeruiz/cf-recycle-plugin/releases.

**Comment by superbeeny** [comment]
Thanks for the issues, I have some tasks to go through and generally update the plugin. Bring the Go release up to date, and add a proper CI process are a couple of them. I should it all completed in the next day or so.

**Comment by rogeruiz** [comment]
@superbeeny, oh great! I added some PRs to my fork if you want to take a look at those. I'm using CircleCI to build the releases, and switched over to `dep` instead of `godep`.

- rogeruiz/cf-recycle-plugin#1
- rogeruiz/cf-recycle-plugin#4

**Comment by superbeeny** [comment]
Thanks I'll take a look, we use a lot of trunk based dev internally and concourse for our builds. I did update to remove Godep and use govendor instead.

**Comment by superbeeny** [comment]
CI process now in place, binaries are now uploaded as part of the build
