### ISSUE TITLE
Stuck in loop waiting for "down"

### ISSUE THREAD

**Issue by kkellner** [Comcast/cf-recycle-plugin#6]
The plugin is stuck in a loop waiting for state "down", however the restart already shutdown and restated the app within the 10 second sleep...    Plugin output:

```
Plugin cf-recycle-plugin 1.1.1 successfully installed.
Rolling restart of app: MyApp
Instance 0 Status: running
Restarting MyApp instance: 0
Instance 0 Status: running
Instance 0 Status: starting
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
Instance 0 Status: running
```

I believe it's stuck in this loop:
https://github.com/Comcast/cf-recycle-plugin/blob/master/cf_recycle_plugin.go#L116

**Comment by superbeeny** [comment]
Hi Kurt,

I don't see the same as you which is quite odd, also I'm not sure what is generating that first line of output. `Rolling restart of app:` isn't part of this codebase 

```sh
➜  tools cf recycle my-service-dev
Instance 0 Status: running
Restarting rally-github-service-dev instance: 0
Instance 0 Status: down
Instance 0 Status: down
Instance 0 Status: running
Instance 1 Status: running
Restarting my-service-dev instance: 1
Instance 1 Status: down
Instance 1 Status: running
Instance 2 Status: running
Restarting my-service-dev instance: 2
Instance 2 Status: down
Instance 2 Status: down
Instance 2 Status: running
Instance 3 Status: running
Restarting my-service-dev instance: 3
Instance 3 Status: down
Instance 3 Status: running
Instance 4 Status: running
Restarting my-service-dev instance: 4
Instance 4 Status: down
Instance 4 Status: down
Instance 4 Status: running
➜  tools cf -v
cf version 6.40.1+85d04488a.2018-10-31
```

**Comment by kkellner** [comment]
The line `Rolling restart of app: MyApp` is part of a bash script -- you can ignore it.

It's a timing issue.  It will work "most" of the time, but on occasion the `restart-app-instance` will run so fast that the down happens in a few seconds followed by startup...  since the polling is happening every 10 seconds, the plugin missed that the app ever went down.   Even if you poll more often, you could still miss the "down" as fast hardware could only have the container down for a fraction of a second before it changed to "starting" state.

I ended up just writing a bash script to do the same thing...   basically it just checks the uptime in seconds of the app and uses that (along with RUNNING state) to determine if it restarted.    Just offering the logic here as a possible solution to the timing issue.

```
#!/bin/bash
#
# The purpose of the script is to perform a rolling-restart
# of a single app.  Meaning it will restart instance 0, wait
# for it to start, then restart instance 1, wait for it to
# start, etc.
#

# Number of seconds an app instance is reporting as uptime 
# which will be considered to have restarted
UPTIME_SECONDS_MAX_CONSIDERED_RESTART=30

# How often do we poll for app instance status
STATUS_POLL_INTERVAL_SECONDS=5

appName=$1

# Check for access_token
if [[ -z "$appName" ]]; then
	echo "appName is needed"
	exit 1
fi

function waitForAppToRestart {
    appIndex=$1
    echo "Wait for instance ${appIndex} to restart"
    while [ 1 ]; do
        # Get the JSON of all instance status
        appStatsJson=$(cf curl /v2/apps/${appGuid}/instances | jq -r ".[\"${appIndex}\"]")
        appState=$(echo ${appStatsJson} | jq -r .state )
        appUptime=$(echo ${appStatsJson} | jq -r .uptime )
        
        echo "Status of app instance ${appIndex}: ${appState} uptime: ${appUptime}"
        if [[ "${appState}" == "RUNNING" && ${appUptime} -lt ${UPTIME_SECONDS_MAX_CONSIDERED_RESTART} ]]; then
            break
        fi
        sleep ${STATUS_POLL_INTERVAL_SECONDS}
    done
}

appGuid=$(cf app ${appName} --guid)
echo appGuid: ${appGuid}

# Get the JSON of all instance status
appStatsJson=$(cf curl /v2/apps/${appGuid}/instances)

# Get the list of app instances (that are RUNNING)
appInstanceIndexes=$(echo ${appStatsJson} | jq -r 'to_entries | map(select(.value.state=="RUNNING")) | .[].key')

# Loop through all the app instances restarting each one
while read -r appIndex; do
    echo "Restart ${appName} with index ${appIndex}"
    cf restart-app-instance "${appName}" ${appIndex}
    waitForAppToRestart ${appIndex}
done <<< "${appInstanceIndexes}"
```

**Comment by superbeeny** [comment]
makes sense, I'll have a look at updating the plugin to check the uptime.

Thanks for bringing this up.

**Comment by rogeruiz** [comment]
Oh interesting. So the application actually restarted too quickly for the timer to work. Thanks @kkellner that logic of checking the uptime is definitely what’s missing to make this a more robust plugin!

**Comment by eloo** [comment]
maybe a solution would be to also listen for `starting`?
Because starting and down are both indicators that the instance was down?
otherwise the interval of polling could be decreased?

**Comment by abdul-fs** [comment]
Pull request is still pending. Its failing constantly while running from CICD. please update.

**Comment by superbeeny** [comment]
If this is reference to #7 then the contributor still needs to sign the CLA

**Comment by superbeeny** [comment]
Hi Guys, I did some digging around and the recycle instance functionality will be native to the cf cli in v7 which is currently in beta, https://twitter.com/dieuthicao/status/1217514603069882368?s=20 . I'll make some updates to support checking the uptime and some other general updates. When the v7 release goes GA I'll likely archive this repository.

**Comment by abdul-fs** [comment]
Hi team, Can you provide any eta of this fix. our recycle jobs are still failing.

**Comment by superbeeny** [comment]
Sorry been a bit busy with the day job, should have this knocked out early next week

**Comment by abdul-fs** [comment]
@superbeeny I dont see the executable format for linux with your latest release.
For example:
https://github.com/Comcast/cf-recycle-plugin/releases/download/v1.1.1/cf-recycle-plugin-linux

**Comment by abdul-fs** [comment]
We are missing with those assets.

**Comment by superbeeny** [comment]
https://github.com/Comcast/cf-recycle-plugin/releases/tag/v2.0.1 now available with assets

**Comment by abdul-fs** [comment]
@superbeeny can you provide the linux version of it. 

examle:
cf-recycle-plugin-linux
8.34 MB
cf-recycle-plugin-osx
8.37 MB
cf-recycle-plugin-win64.exe
8.22 MB
Source code
(zip)
Source code
(tar.gz)

**Comment by superbeeny** [comment]
it's there just unzip/untar the tgz file.

**Comment by abdul-fs** [comment]
@superbeeny Its go lang. can you please update the release with linux64 version.

**Comment by superbeeny** [comment]
download this file "cf-recycle-plugin-2.0.1.tgz" and unzip/untar, inside are the binaries for the plugin in mac,win,linux flavours
